hydra:
  run:
    dir: .
  output_subdir: null

exp_name: "qwen2.5-7B-rubric-config"
seed: 42
logging_dir: ./output/logs
output_dir: ./output
system_envs:
  USE_MODELSCOPE: '1'

checkpoint_config:
  type: mos

track_with: ml_tracker
tracker_kwargs:
 project: roll_qwen2.5_7B_rubrics
 notes: roll_qwen2.5_7B_rubrics
 tags:
   - rlvr
   - baseline

num_gpus_per_node: 8

max_steps: 500
save_steps: 20
logging_steps: 1
eval_steps: 10
resume_from_checkpoint: false

rollout_batch_size: 64  # prompt
prompt_length: 2048
response_length: 2048

num_return_sequences_in_group: 8
ppo_epochs: 1
adv_estimator: "grpo"

# clip
pg_clip: 0.2                    # 裁剪范围
pg_clip_low: 0.2               # 下界裁剪（可选）
pg_clip_high: 0.27             # 上界裁剪（可选）
use_pg_clip_range: true       # 是否使用不对称裁剪
dual_clip_loss: false           # 是否启用双重裁剪

# normalize
norm_mean_type: group
norm_std_type: group

# data mask
max_len_mask: false
difficulty_mask: false
difficulty_low_threshold: -1
difficulty_high_threshold: 1
error_max_len_clip: false

# data weight
difficulty_loss_weight: false
length_loss_weight: false

# reward
init_kl_coef: 0
enable_reference: false
add_token_level_kl: false
reward_union_type: all-or-nothing

# advantage
whiten_advantages: false

pretrain: Qwen/Qwen2.5-7B-Instruct
reward_pretrain: deepseek-ai/DeepSeek-V3.1 

actor_train:
  model_args:
    disable_gradient_checkpointing: false
    dtype: bf16
    model_type: ~
  training_args:
    learning_rate: 1.0e-6
    weight_decay: 0
    per_device_train_batch_size: 4
    gradient_accumulation_steps: 2
    warmup_steps: 20
    num_train_epochs: 50
  data_args:
    template: qwen2_5
    file_name:
      - data/HIR_trainv1_rubrics_processed.jsonl
    domain_interleave_probs:
      llm_judge: 1.0
    dataset_dir: data
    messages: messages
    interleave_probs: "1.0"
    preprocessing_num_workers: 16
  strategy_args:
    strategy_name: megatron_train
    strategy_config:
      tensor_model_parallel_size: 1
      pipeline_model_parallel_size: 1
      expert_model_parallel_size: 1
      use_distributed_optimizer: true
      recompute_granularity: full
  device_mapping: list(range(0,32))
  infer_batch_size: 4

actor_infer:
  model_args:
    disable_gradient_checkpointing: true
    dtype: bf16
  generating_args:
    max_new_tokens: ${response_length}
    top_p: 0.99
    top_k: 100
    num_beams: 1
    temperature: 0.99
    num_return_sequences: ${num_return_sequences_in_group}
  data_args:
    template: qwen2_5
  strategy_args:
    strategy_name: vllm
    strategy_config:
      gpu_memory_utilization: 0.8
      block_size: 16
      max_model_len: 8000
  device_mapping: list(range(0,32))
  infer_batch_size: 1


rewards:
  llm_judge:
    # NOTE: llm as judge 也需要gpu, 不能和actor infer共享gpu
    worker_cls: roll.pipeline.rlvr.rewards.rubrics_llm_judge_reward_worker.RubricsLLMJudgeRewardWorker
    judge_model_type: inference
    tag_included: [llm_judge]
    model_args:
      model_name_or_path: ${reward_pretrain}
      disable_gradient_checkpointing: true
      dtype: bf16
    generating_args:
      max_new_tokens: 512
      top_p: 0.01
      top_k: 1
      num_beams: 1
      temperature: 0.01
      num_return_sequences: 1
    data_args:
      template: native
    strategy_args:
      strategy_name: vllm
      strategy_config:
        tensor_parallel_size: 8
        gpu_memory_utilization: 0.9
        block_size: 16
        max_model_len: 6000
        load_format: auto
    device_mapping: list(range(32,64))
    infer_batch_size: 4